
1. генерация матриц по размерам

2. вывод результатов

3. перемножение библиотекой

4. перемножение руками

5. сравнение руками и библиотекой

In [2]:
import numpy as np

# 1. генерация матриц по размерам


Создание целочисленной матрицы

In [9]:
np.random.randint(0, 6, (3, 3))


array([[1, 3, 0],
       [5, 2, 2],
       [2, 4, 0]])

Создание матрицы с вещественными значениями

In [10]:
np.random.rand(4, 2)




array([[0.35430253, 0.1318987 ],
       [0.67980799, 0.25534195],
       [0.77075493, 0.0737411 ],
       [0.24033872, 0.38587414]])

# 2. вывод результатов

Никуя не понял, уже вывел все значения в задании 1:)

# 3. перемножение библиотекой


Создание двух матриц

In [12]:

p = [[1, 2], [2, 3], [4, 5]]
q = [[4, 5, 1], [6, 7, 2]]

print(p)
print(q)

[[1, 2], [2, 3], [4, 5]]
[[4, 5, 1], [6, 7, 2]]


Умножение матриц c помощью встроенной функции **dot**

In [15]:
multiplication = np.dot(p, q)
multiplication

array([[16, 19,  5],
       [26, 31,  8],
       [46, 55, 14]])

# 4. перемножение руками

Создание матриц

In [16]:

p = [[1, 2], [2, 3], [4, 5]]
q = [[4, 5, 1], [6, 7, 2]]

print(p)
print(q)

[[1, 2], [2, 3], [4, 5]]
[[4, 5, 1], [6, 7, 2]]


Возможный вариант перемножения матриц вручную

In [52]:
def matrices_mult(m1, m2): 
     res = [[sum(a * b for a, b in zip(m1_row, m2_col))
          for m2_col in zip(*m2)] for m1_row in m1]
     for r in res:
          print(r)

In [53]:
matrices_mult(p, q)

[16, 19, 5]
[26, 31, 8]
[46, 55, 14]


# 5. сравнение руками и библиотекой

Тоже никуя не понял, можно просто сравнить одной строчкой две матрицы вот так:

In [56]:
p = [[1, 2], [2, 3], [4, 5]]
p1 = [[1, 2], [2, 3], [4, 5]]
q = [[4, 5, 1], [6, 7, 2]]

In [57]:
p == q

False

In [59]:
p1 == p

True